// Rebuild offline data from the original toolkit libraries and the checked-in hero snapshot.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8').replace(/^\uFEFF/, '');
const write = (file, content) => fs.writeFileSync(path.join(root, file), content);
const symbols = JSON.parse(read('data/symbols.json'));
const library = `const SYMBOL_LIB = ${JSON.stringify(Object.fromEntries(Object.entries(symbols).map(([name, chars]) => [name, Array.from(chars)])), null, 2)};`;
// Keep the standalone libraries in sync with the site's curated catalog.
const pixel = read('tools/pixel-ascii-editor.html').replace(
  /const SYMBOL_LIB = [\s\S]*?(?=const TOOLS = )/,
  `${library}\n\n`
);
write('tools/pixel-ascii-editor.html', pixel);
write('data/symbols.txt', Object.values(symbols).join('\n') + '\n');
const frames = pixel.slice(
  pixel.indexOf('const FRAME_STYLES = '),
  pixel.indexOf('/* ============ СОСТОЯНИЕ')
);
const heroes = Object.values(JSON.parse(read('data/heroes-source.json')))
  .map((h) => ({
    id: h.id,
    name: h.localized_name,
    attr: h.primary_attr,
    roles: h.roles,
    attack: h.attack_type,
    portrait: `assets/portraits/${h.id}.${['jpg', 'png', 'webp'].find((ext) => fs.existsSync(path.join(root, `assets/portraits/${h.id}.${ext}`)))}`
  }))
  .sort((a, b) => a.name.localeCompare(b.name));
const presets = JSON.parse(read('presets/presets.json')).presets;
write(
  'scripts/data.mjs',
  `// Generated by scripts/build-data.cjs. See assets/ATTRIBUTION.md.\n${library}\n${frames}\nexport default { heroes: ${JSON.stringify(heroes)}, symbols: SYMBOL_LIB, frames: FRAME_STYLES, presets: ${JSON.stringify(presets)} };\n`
);
const original = read('tools/lineart-converter.html').replace(
  /const LIBRARY = [\s\S]*?(?=const DOTA_W = )/,
  `const LIBRARY = ${JSON.stringify(
    Object.entries(symbols).map(([name, chars]) => ({ id: name, name, chars })),
    null,
    2
  )};\n\n`
);
write('tools/lineart-converter.html', original);
let algorithms = original.slice(
  original.indexOf('function gaussianBlur('),
  original.indexOf('function applyPreset(')
);
// A blank image has zero gradient and must not become an entirely filled edge map.
algorithms = algorithms.replace(
  'const hi=max*high, lo=max*low;',
  'if (max <= 1e-8) return new Uint8Array(W*H);\n    const hi=max*high, lo=max*low;'
);
write(
  'scripts/edges.mjs',
  `// Canny + Zhang-Suen algorithms from the original MIT-licensed Line-Art Converter.\n// Extracted for use by both the browser converter and Node tests.\n${algorithms}\nexport { gaussianBlur, sobel, nonMaxSuppression, hysteresis, thinning, angleToChar, spatialSample };\n`
);
